export const LABELS = {
  tabs: {
    calculator: 'Калькулятор',
    distribution: 'Распределение людей',
    research: 'Исследование',
  },
  input: {
    kloc: 'Kloc (тысячи строк кода)',
    budget: 'Бюджет на человеко-месяц',
    calculate: 'Рассчитать',
  },
  mode: {
    label: 'Режим COCOMO',
    basic: 'Базовый',
    intermediate: 'Промежуточный',
    embedded: 'Встроенный',
  },
  attributes: {
    program: 'Атрибуты программного продукта',
    computer: 'Атрибуты компьютера',
    staff: 'Атрибуты персонала',
    project: 'Атрибуты проекта',
    rely: 'RELY: требуемая надёжность',
    data: 'DATA: Размер БД',
    cplx: 'CPLX: Сложность',
    time: 'TIME: Ограничение времени',
    stor: 'STOR: Ограничение памяти',
    virt: 'VIRT: Изменчивость виртуальной машины',
    turn: 'TURN: Время отклика',
    acap: 'ACAP: Аналитические способности',
    aexp: 'AEXP: Опыт разработки',
    pcap: 'PCAP: Способности к программированию',
    vexp: 'VEXP: Опыт виртуальных машин',
    lexp: 'LEXP: Опыт языка программирования',
    modp: 'MODP: Современные практики программирования',
    tool: 'TOOL: Использование инструментов',
    sced: 'SCED: Требуемые сроки разработки',
  },
  levels: {
    VL: 'Очень низкий',
    L: 'Низкий',
    N: 'Номинальный',
    H: 'Высокий',
    VH: 'Очень высокий',
  },
  results: {
    title: 'Результаты',
    workAndTime: 'Трудозатраты и сроки',
    budget: 'Бюджет',
    activity: 'Тип активности',
    workPercent: 'Трудозатраты, %',
    workMonths: 'Трудозатраты, чел.-мес.',
    timePercent: 'Срок, %',
    timeMonths: 'Срок, мес.',
    budgetPercent: 'Доля в бюджете, %',
    budgetAmount: 'Бюджет, ден. ед.',
    total: 'Итого',
  },
  activities: {
    planning: 'Планирование и определение требований',
    design: 'Проектирование продукта',
    construction: 'Детальное преоктирование',
    codingTesting: 'Кодирование и тестирование',
    integrationTesting: 'Интеграция и тестирование',
    analysis: 'Анализ требований',
    programming: 'Программирование',
    testPlanning: 'Планирование тестирования',
    verification: 'Верификация',
    office: 'Канцелярия',
    configManagement: 'Управление конфигурацией',
    documentation: 'Документация',
  },
}